---
title: "CV - Conner Smith"
---

<a href = "smith_conner_cv.pdf" target = '_blank'>Click here for the full CV</a>

### **Fellow – Sustainable Ocean Alliance/Environmental Defense Fund, Remote, Santa Barbara, CA (6/22–Present)**
- Awarded $10k micro-grant through the Leadership for Climate-Resilient Fisheries Fellowship 
- Synthesizing research on Indigenous-led fisheries, aquaculture, and coastal management initiatives
- Working to leverage science promoting Native leadership and co-management strategies


### **Researcher – The Nature Conservancy, Remote, Santa Barbara, CA (6/22–8/22)**
- Worked on contract with TNC staff to research kelp forest restoration activities
- Interviewed two dozen government, non-profit, industry, and private stakeholders to assess urchin removal methods and costs
- Produced a report identifying key opportunities to grow urchin removal workforce at a program scale


### **Researcher – Ocean Analytics, Santa Barbara, CA (11/21–8/22)**

- Conducted comprehensive analysis of all 46 federally managed fisheries in the United States to develop the first nationwide review of prevailing management strategies 
- Article published in Fish and Fisheries in December 2022 
- Leveraged R software to process fishery stock assessment data and perform analyses to identify effectiveness of policies aimed at ensuring sustainability of international high seas fisheries 


### **Policy Analyst – Atlas Public Policy, Remote, SF Bay Area (4/21–6/21)**

- Directed research, data collection, and writing for two reports funded by a large trade association 
identifying climate, environmental justice, and economic opportunities of transportation electrification 
- Managed project proposals for five figure contracts with partners including NGO, government, and private 
sector entities seeking to develop a living database of climate policies in the U.S.
- Leveraged original research and data collection to publish data-based storytelling funded by key players in 
the electric vehicle (EV) and environmental policy spaces

### **Policy Associate – Atlas Public Policy, Remote, SF Bay Area (2/19–4/21)**

- Led data collection and outreach for the Atlas EV Hub, a subscription-based platform that grew from 500 
to more than 1,000 professional users over this time
- Assisted with a six figure, government-funded analysis of widespread fleet electrification across all public 
vehicles in the state of Washington, revealing that the state could cost effectively electrify nearly all 
vehicles by 2035
- Published more than 10 research papers funded by partnerships with stakeholders in the clean 
transportation space

### **Program Associate – Clinton Foundation, New York, NY (6/17–10/18)**

- Simulated a country-wide adoption of 100 percent renewable energy in Belize using excel and HOMER 
software, culminating in several presentations to more than 10 elected officials 
- Conducted research under a $5 million grant with partners at the Rocky Mountain Institute to develop long 
term clean energy roadmaps for island nations
- Helped secure millions of dollars in commitments from Clinton Global Initiative member organizations 
targeting disaster relief and climate resilience in regions impacted by devastating hurricanes in 2017
- Prepared more than 50 research and policy memos for President Clinton and foundation leadership to 
inform internal policy and data collection across the Foundation


