---
name: Conner
surname: Smith
position: "Master's Student"
address: "Bren School of Environmental Science and Management"
phone: +1 704 654 1514
email: "connersmith@bren.ucsb.edu"
github: connermuir
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(rorcid)
library(tibble)
library(tinytex)
```


# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Environmental Science and Management", "2023 (Expected)", "University of Califonria at Santa Barbara", "Santa Barbara, California",
  "Bachelor of Science in Environmental Economics and Policy", "2017", "University of California at Berkeley", "Berkeley, California",
  "Bachelor of Arts in Global Development Studies", "2017", "University of California at Berkeley", "Berkeley, California"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Experience

```{r}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Fellow", "Sustainable Ocean Alliance/Environmental Defense Fund", "Remote, Santa Barbara, California", "Jun. 2022 - Present", 
    list("Awarded $10k micro-grant through the Leadership for Climate-Resilient Fisheries Fellowship",
         "Synthesizing research on Indigenous-led fisheries, aquaculture, and coastal management initiatives", "Working to leverage science promoting Native leadership and co-management strategies"
    ),
  "Researcher", "The Nature Conservancy", "Remote, Santa Barbara, California", "Jun. 2022 - Aug. 2022", 
    list("Worked on contract with TNC staff to research kelp forest restoration activities",
         "Interviewed two dozen government, non-profit, industry, and private stakeholders to assess urchin removal methods and costs", "Produced a report identifying key opportunities to grow urchin removal workforce at a program scale"
    ),
"Researcher", "Ocean Analytics", "Santa Barbara, California", "Nov. 2021 - Aug. 2022", 
    list("Conducted comprehensive analysis of all 46 federally managed fisheries in the United States to develop the 
first nationwide review of prevailing management strategies",
         "Article published in Fish and Fisheries in December 2022", "Leveraged R software to process fishery stock assessment data and perform analyses to identify effectiveness of policies aimed at ensuring sustainability of international high seas fisheries"
    ),
  "Policy Analyst", "Atlas Public Policy", "Oakland, California", "Feb. 2019 - June 2020", 
    list("Directed research, data collection, and writing for two reports funded by a large trade association 
identifying climate, environmental justice, and economic opportunities of transportation electrification", 
         "Managed project proposals for five figure contracts with partners including NGO, government, and private 
sector entities seeking to develop a living database of climate policies in the U.S",
         "Led data collection and outreach for the Atlas EV Hub, a subscription-based platform that grew from 500 
to more than 1,000 professional users over this time
", "Published more than 10 research papers funded by partnerships with stakeholders in the clean transportation space"),
  "Program Associate", "Clinton Foundtion", "New York, New York", "June 2017 - October 2018", list("Simulated a country-wide adoption of 100 percent renewable energy in Belize using excel and HOMER software, culminating in several presentations to more than 10 elected officials", "Conducted research under a $5 million grant with partners at the Rocky Mountain Institute to develop long term clean energy roadmaps for island nations", "Helped secure millions of dollars in commitments from Clinton Global Initiative member organizations targeting disaster relief and climate resilience in regions impacted by devastating hurricanes in 2017")
) %>% 
  detailed_entries(role, dates, company, loc, details)
```

