---
title: "The Case for Native-led Forest Management in California"
description: |
 Partnerships between Native Californians and state agencies are one step that can lead towards greater coexistence with this natural element of the California landscape.
author:
  - name: Conner Smith
date: 2022-02-03
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Fires are burning hotter and longer throughout California, prompting forest managers to ask the question, Is “fire season” a thing of the past? Cal Fire, the agency responsible for monitoring and responding to a majority of wildfire activity, estimates that the traditional fire season [which typically peaks between July and October] has already expanded by 75 days throughout the Sierra Nevada. In 2021, the agency tracked fires from Santa Barbara to the Oregon border, and as of year’s end, 2.6 million acres of forest had burned.  Both climate change and management regimes focused on fire suppression at any cost have created this new age of almost annual super fires. This is forcing state officials to question prevailing narratives and acknowledge a dark environmental past ─ namely, the exclusion of Native Californians and their traditional practices from modern forest management.

### What is Fanning the Flames? 

Leading fire ecologists point to multiple drivers of hotter and bigger blazes, which are expected in the coming decades. Max Moritz, a fire specialist for the UC Cooperative Extension Program, has spent years predicting future fire risk around the globe. The Moritz Lab models show that “one of the most striking salient predictions is that fire activity will increase across much of the northern hemisphere.” 

Climate change is driving what experts are calling a “megadrought” throughout the American West. Two decades of abnormally dry conditions have contributed to mass tree die-off, creating a buildup of dry and dead material throughout forest landscapes. This is helping drive higher intensity fires– four of the five largest fires in California history were ignited in 2020. 

Climate change is not the only factor driving more devastating fires throughout California. Some are turning a critical eye to the role that management decisions, and specifically wildland fire suppression, play in exacerbating the risk of super fires. 
Researchers at the Bren School of Environmental Science and Management question the efficacy of a fire management strategy focused primarily on disaster response. Reactionary policy centered around suppressing fires has led to higher forest density, and consequently higher fire risk as forests become crowded and lose natural fuel breaks. A one-sided focus on mitigating fires when they break out has also led to missed opportunities to preemptively reduce the risk of fire in unburned areas. 

Moritz stresses that management decision and climate change are only threads in a larger story concerning wildfire in the American West.  He argues that “in contrast to other natural hazards, the primary response is to fight fires rather than to accept them as a recurring fact of life in fire-prone ecosystems.” 

### A Brighter Future, Out of a Dark Past 

Reimagining our relationship to fire and reintroducing burning to wildland areas where it has been suppressed could enhance resilience to climate change for both forest and human systems. Some are calling for the re-integration of traditional practices like controlled burns and strategic forest thinning. 

Despite centuries of proven expertise, Native communities have long been excluded from decisions around land and resource management in California. Violent removal of Native communities from ancestral lands and categorical underestimates of the ecological benefits of traditional practices have contributed to a shortsighted wildland management approach. This pattern is especially evident in Yosemite, where the expulsion of the Ahwahneechee went hand-in-hand with the adoption of a conservation strategy built around the idea of “untouched wilderness.” 

This management approach has led to a loss of biodiversity and increased fire risk in the region. Worse is the displacement and profound cultural loss for Native Californians.  For many tribes, cultural identity is at stake as important food and ceremonial resources suffer when fire is removed from the landscape. 

Wildfire is one driver amplifying the call to right past wrongs and restore Native land management rights throughout California. Members of tribes from the Yurok and Karuk on the redwood coast to the North Fork Mono in the Sierra foothills are calling state officials to account and seeking cooperation. “I would like to be able to use modern tools and our ancestral knowledge and integrate it with Western science so we can restore the natural landscape,” says Karuk natural resources director Bill Tripp.

Native communities have long understood the importance of revitalizing forest understory with “good fire.” Yurok basket weaver and fire management leader Margo Robbins puts it simply, “we must have fire in order to continue the traditions of our people.” A growing body of Western scientific research is beginning to catch up with the long-held knowledge of supporting what Native communities have long understood. 

Stanford researchers working in partnership with Native managers in the Klamath region showed that controlled or “cultural” burning produced a multitude of ecological and social benefits. Burning on study plots not only produced superior hazelnut branches, an item of cultural significance for basket weaving, but also reduced fire risk and enhanced biodiversity. 

Data on current and historical fire patterns, as well as models predicting future trends, shows gaping holes in our understanding of changing forest dynamics. Recognition of the advantages of traditional practices like controlled burning is emerging within the California state management apparatus. Governor Newsom’s 2021-2022 budget allocates $20 million to support Native burning programs. 

Policymakers, communities, and fire experts are coalescing around an agreement that a multitude of practices will be needed in order to address the challenges associated with a more fiery future.  Partnerships between Native Californians and state agencies are one step that can lead towards greater coexistence with this natural element of the California landscape. 

### References

1) Cal Fire. Incidents Overview (2021).

2) Max Moritz. “Coexisting with Wildfires.” American Scientist (2016).

3) Sarah Anderson et al. "The dangers of disaster-driven responses to climate change." Nature Climate Change (2018): 648-659.

4) Rochelle Bloom, Douglas Deur. "Through a Forest Wilderness: Native American Environmental Management at Yosemite and Contested Conservation Values in America’s National Parks.” Portland State University (2020).

5) Western Regional Strategy Committee (WRSC). “Western Regional Risk Report.” (2012).

6) David Helvarg. “Using Fire to Fight Fire: California Tribes' Cultural Burns Restore Land and Keep Flames at Bay.” American Indian Magazine (2021).

7) Rob Jordan. “Native approaches to fire management could revitalize communities, Stanford researchers find.” Stanford University (2019). 



